---
- name: "Manage docker configs"
  community.docker.docker_config:
    docker_host: "{{ docker_host | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    ca_cert: "{{ ca_cert | default(omit) }}"
    client_key: "{{ client_key | default(omit) }}"
    client_cert: "{{ client_cert | default(omit) }}"
    name: "{{ item['name'] | mandatory }}"
    data: "{{ item['data'] | mandatory }}"
    data_is_b64: "{{ item['b64'] | default(omit) }}"
    labels: "{{ item['labels'] | default(omit) }}"
    state: "{{ item['state'] | default(omit) }}"
  loop: "{{ docker_configs }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
  run_once: true
