---
- name: "Manage docker container"
  community.docker.docker_container:
    docker_host: "{{ docker_host | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    ca_cert: "{{ ca_cert | default(omit) }}"
    client_key: "{{ client_key | default(omit) }}"
    client_cert: "{{ client_cert | default(omit) }}"
    command: "{{ item['command'] | default(omit) }}"
    container_default_behavior: "{{ item['container_default_behavior'] | default(omit) }}"
    detach: "{{ item['detach'] | default(omit) }}"
    dns_opts: "{{ item['dns_opts'] | default(omit) }}"
    dns_search_domains: "{{ item['dns_search_domains'] | default(omit) }}"
    dns_servers: "{{ item['dns_servers'] | default(omit) }}"
    domainname: "{{ item['domainname'] | default(omit) }}"
    entrypoint: "{{ item['entrypoint'] | default(omit) }}"
    env: "{{ item['env'] | default(omit) }}"
    env_file: "{{ item['env_file'] | default(omit) }}"
    etc_hosts: "{{ item['etc_hosts'] | default(omit) }}"
    name: "{{ item['name'] | mandatory }}"
    image: "{{ item['image'] | default(omit) }}"
    pull: "{{ item['pull'] | default(omit) }}"
    hostname: "{{ item['hostname'] | default(omit) }}"
    healthcheck: "{{ item['healthcheck'] | default(omit) }}"
    mounts: "{{ item['mounts'] | default(omit) }}"
    networks: "{{ item['networks'] | default(omit) }}"
    network_mode: "{{ item['network_mode'] | default(omit) }}"
    purge_networks: "{{ item['purge_networks'] | default(omit) }}"
    published_ports: "{{ item['published_ports'] | default(omit) }}"
    restart: "{{ item['restart'] | default(omit) }}"
    restart_policy: "{{ item['restart_policy'] | default(omit) }}"
    restart_retries: "{{ item['restart_retries'] | default(omit) }}"
    stop_signal: "{{ item['stop_signal'] | default(omit) }}"
    stop_timeout: "{{ item['stop_timeout'] | default(omit) }}"
    storage_opts: "{{ item['storage_opts'] | default(omit) }}"
    tmpfs: "{{ item['tmpfs'] | default(omit) }}"
    tty: "{{ item['tty'] | default(omit) }}"
    volume_driver: "{{ item['volume_driver'] | default(omit) }}"
    volumes: "{{ item['volumes'] | default(omit) }}"
    volumes_from: "{{ item['volumes_from'] | default(omit) }}"
    working_dir: "{{ item['working_dir'] | default(omit) }}"
    privileged: "{{ item['privileged'] | default(omit) }}"
    user: "{{ item['user'] | default(omit) }}"
    groups: "{{ item['groups'] | default(omit) }}"
    labels: "{{ item['labels'] | default(omit) }}"
    state: "{{ item['state'] | default(omit) }}"
  loop: "{{ docker_containers }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('started') }}"
