---
- name: "Create workdir"
  tags: docker.image.dockerfile
  ansible.builtin.file:
    state: directory
    path: "{{ item['path'] | dirname }}"
  loop: "{{ docker_builds }}"
  loop_control:
    label: "{{ item['path'] }}"

- name: "Copy files to include in image build"
  tags: docker.image.copy
  ansible.builtin.copy:
    src: "{{ item['copy']['src'] }}"
    dest: "{{ item['copy']['dest'] }}"
    local_follow: false
  loop: "{{ docker_builds | selectattr('copy','defined') }}"
  loop_control:
    label: "{{ item['copy']['src'] }} => {{ item['copy']['dest'] }}"

- name: "Create Dockerfile"
  tags: docker.image.dockerfile
  ansible.builtin.template:
    src: Dockerfile.ji2
    dest: "{{ item['path'] }}"
  loop: "{{ docker_builds }}"
  loop_control:
    label: "{{ item['path'] }}"

- name: "Manage image"
  tags: docker.image.manage
  community.docker.docker_image:
    name: "{{ item['name'] | mandatory }}"
    tag: "{{ item['tag'] | default(omit) }}"
    source: "{{ item['source'] | mandatory }}"
    repository: "{{ item['repository'] | default(omit) }}"
    force_tag: "{{ item['force_tag'] | default(omit) }}"
    build: "{{ item['build'] | default(omit) }}"
  loop: "{{ docker_images }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
