---
- name: "Manage docker secret"
  tags:
    - docker
    - docker.secret
  ansible.builtin.import_tasks: secret.yaml

- name: "Manage docker stack"
  tags:
    - docker
    - docker.stack
  ansible.builtin.import_tasks: stack.yaml

- name: "Build docker image"
  tags:
    - docker
    - docker.build
  ansible.builtin.import_tasks: build.yaml
