---
- name: "Build docker images"
  tags:
    - docker
    - docker.image
  ansible.builtin.import_tasks: image.yaml

- name: "Manage docker configs"
  tags:
    - docker
    - docker.config
  ansible.builtin.import_tasks: config.yaml

- name: "Manage docker secrets"
  tags:
    - docker
    - docker.secret
  ansible.builtin.import_tasks: secret.yaml

- name: "Manage docker volumes"
  tags:
    - docker
    - docker.volume
  ansible.builtin.import_tasks: volume.yaml

- name: "Manage docker container"
  tags:
    - docker
    - docker.container
  ansible.builtin.import_tasks: container.yaml

- name: "Manage docker stacks"
  tags:
    - docker
    - docker.stack
  ansible.builtin.import_tasks: stack.yaml
