---
- name: "Manage docker volumes"
  community.docker.docker_config:
    docker_host: "{{ docker_host | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    ca_cert: "{{ ca_cert | default(omit) }}"
    client_key: "{{ client_key | default(omit) }}"
    client_cert: "{{ client_cert | default(omit) }}"
    name: "{{ item['name'] | mandatory }}"
    driver: "{{ item['driver'] | default(omit) }}"
    driver_options: "{{ item['driver_options'] | default(omit) }}"
    labels: "{{ item['labels'] | default(omit) }}"
    recreate: "{{ item['recreate'] | mandatory }}"
    state: "{{ item['state'] | default(omit) }}"
  loop: "{{ docker_volumes }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
  run_once: true
